dist: xenial
language: python
sudo: true

python:
  - 3.7
  - 3.8
  - 3.9

env:
  global:
    - CRYPTOGRAPHY_DONT_BUILD_RUST=1
  jobs:
    - DJANGO=2.2
    - DJANGO=3.0
    - DJANGO=3.1
    - DJANGO=3.2

install:
  - pip install tox-travis
  - pip install "coverage<=4.0" codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}"

after_success:
  - coverage combine
  - codecov
