[pytest]
pythonpath=./tests/demoapp/
django_find_project = false
DJANGO_SETTINGS_MODULE=demo.settings
norecursedirs = .tox docs ./demo/
python_files=test_*.py
doctest_optionflags=ELLIPSIS ALLOW_UNICODE ALLOW_UNICODE
addopts =

        -p no:warning
        --reuse-db
        --doctest-modules
        --tb=short
        --capture=no
        --echo-attr django.conf.settings.DATABASES.default.ENGINE
        --cov-report=html
        --cov-config=tests/.coveragerc
        --cov smart_admin

markers =
    functional: mark a test as functional
