[tox]
requires =
    tox>=4.2
    tox-gh-actions
    tox-uv>=1.20.2
env_list =
    lint
    py{313, 312}-d{52, 42}
    pkg_meta
no_package = false
skip_missing_interpreters = true

[testenv]
extras =
    sysinfo
set_env =
    PYTHONDONTWRITEBYTECODE = true
    d42: django = 4.2
    d52: django = 5.2
commands =
    uv pip install django~={env:django}
    {posargs:pytest tests -rw --create-db}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:pkg_meta]
description = check that the long description is valid
skip_install = true
deps =
    check-manifest
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    uv build --sdist --wheel --out-dir {env_tmp_dir} .
    twine check {env_tmp_dir}{/}*
    check-wheel-contents --no-config {env_tmp_dir} --ignore W002,W004

[testenv:type]
description = run type check on code base
commands =
    mypy --strict {posargs:src/}
dependency_groups = dev

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
