# Generated by Django 3.2.6 on 2021-08-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel1',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Other email'),
        ),
    ]
